INSERT INTO CAT_UNIT (UNT_NAME, UNT_CODE) VALUES ('l','01');
INSERT INTO CAT_UNIT (UNT_NAME, UNT_CODE) VALUES ('g','02');
INSERT INTO CAT_UNIT (UNT_NAME, UNT_CODE) VALUES ('menge','03');

INSERT INTO INGREDIENT ( ING_NAME ) VALUES ('Mehl');
INSERT INTO INGREDIENT ( ING_NAME ) VALUES ('Eier');
INSERT INTO INGREDIENT ( ING_NAME ) VALUES ('Zucker');
INSERT INTO INGREDIENT ( ING_NAME ) VALUES ('Milch');

INSERT INTO RECIPE  ( REC_NAME  ) VALUES ('Kuchen');
INSERT INTO RECIPE ( REC_NAME ) VALUES ('Pfannkuchen');

INSERT INTO RECIPE_INGREDIENT (REC_ID , ING_ID, RET_CAT_UNIT, RET_DESCRIPTION) VALUES 
(( Select REC_ID  FROM RECIPE WHERE REC_NAME  = 'Kuchen'), (Select ING_ID  FROM INGREDIENT WHERE ING_NAME  = 'Mehl'), '02', '250'),
(( Select REC_ID  FROM RECIPE WHERE REC_NAME  = 'Kuchen'), (Select ING_ID  FROM INGREDIENT WHERE ING_NAME  = 'Eier'), '03','2'),
(( Select REC_ID  FROM RECIPE WHERE REC_NAME  = 'Kuchen'), (Select ING_ID  FROM INGREDIENT WHERE ING_NAME  = 'Milch'), '01','100');